/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internal;

import javafx.scene.control.Tab;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author micha
 */
public class SaveLoadFrame extends javax.swing.JFrame {
    Frame inputFrame;
    String tag="";
    JPanel inputPanel;
    /**
     * Creates new form SaveLoadFrame
     */
    public SaveLoadFrame(Frame frame, String tag, JPanel p) {
        initComponents();
        inputFrame=frame;
        this.tag=tag;
        inputPanel=p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        dayButton = new javax.swing.JButton();
        excercisePlanButton = new javax.swing.JButton();
        mealButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        dayButton.setText("Day");
        dayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayButtonActionPerformed(evt);
            }
        });

        excercisePlanButton.setText("Excercises");
        excercisePlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excercisePlanButtonActionPerformed(evt);
            }
        });

        mealButton.setText("Meal");
        mealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dayButton)
                .addGap(18, 18, 18)
                .addComponent(mealButton)
                .addGap(18, 18, 18)
                .addComponent(excercisePlanButton)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(dayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mealButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(excercisePlanButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayButtonActionPerformed
        if(tag.equals(Tags.SAVE)){ //check tag
            if(inputFrame.day.getMeals().length+inputFrame.day.getExcercises().length>0){ //check if day is not empty
        inputFrame.saveDay(); // call save function
            }else{
            JOptionPane.showMessageDialog(this, "Your day is empty"); // inform the user their day is empty
            }
        }
        if(tag.equals(Tags.LOAD)){ // check tag
        inputFrame.loadDay(); // call function that loads the object
        inputFrame.updateMealList(); // call function that updates meal list in main frame
        inputFrame.updateExcercisePlanList(); // call function that updates excercise plan list in main frame
        }
        this.update(); // call functions that updates tips, fields and UI in main frame trhough a function in this frame
        this.dispose(); // close this frame
    }//GEN-LAST:event_dayButtonActionPerformed

    private void mealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealButtonActionPerformed
        if(tag.equals(Tags.SAVE)){
        inputFrame.saveMeal();
        }
        if(tag.equals(Tags.LOAD)){
        inputFrame.loadMeals();
        }
        this.update();
        this.dispose();
    }//GEN-LAST:event_mealButtonActionPerformed

    private void excercisePlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excercisePlanButtonActionPerformed
         if(tag.equals(Tags.SAVE)){
        inputFrame.saveExcercises();
        }
        if(tag.equals(Tags.LOAD)){
        inputFrame.loadExcercises();
        }
        this.update();
        this.dispose();
    }//GEN-LAST:event_excercisePlanButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.update();
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    

     
    }
    public void update(){
    inputFrame.updateFields();
    inputFrame.updateTips();
    inputPanel.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton dayButton;
    private javax.swing.JButton excercisePlanButton;
    private javax.swing.JButton mealButton;
    // End of variables declaration//GEN-END:variables
}
